export const pazuzu = `
MMMMWNNNNWMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWN
MMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMWWWWWMMMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
NNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMWXxldXMMMMMNKKNMMMMMMWWNWWWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWW
NNNNWMMMMWNNWWMMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNWWMWNOl,...oWMMNk:'.:oOWMMMMMMMMMMMMMWWNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMMMWWWWWMMMWNNNNWW
WWWWWWNNNWWMMMMMMMMWWWWWWNNNWWWWWWWNNNWWWWWWNNNWWWWWWWNNNWWWWWWWNNNWWWWWWWNNNWWWWWWNNNNWWWWWWNNNWWWWWWWWNNWWWWWWWNNNWWWWWWWNNWWWMMW0l,..... ,kko:'''.  'OWMMMXklclx0XWMMWWMMMWNNWWWWWWNNNNWWWWWWNNNWWWWWWWNNNWWWWWWWNNNWWWWWWNNNNWWWWWWNNNWWWWWWWNNNWWWWWWWNNNWWWMWWNNNNWWWWWWNNNWWWWWWMMMNOxKWMWWNNNWWWWWWW
MMMMWNNNNWMMMNxcxNMMMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMWNNNWWMW0c.....     .. .....   'kN0o;......,:ldONWMMWNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWKd,. ,OMMWNNNNWMMMWN
WWWWWWWWWWWMMN:  ;dOXMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWKo.           ...         .;,.'''...''....,cOWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMXd.  ...:XMMWWWWWWWWWW
NNNNWMMMMWNWMNc     'oKMMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWWWWMMMW0l.        .                ......     ...''. lNMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMMMW0:   .....OMMMMMWNNNNWM
NNNNWMMMWWWMWK; ..    'oKWMMWWNNNWWMMMWNNNNWMMMWWNNNNWMMMWWNNNNWMMMWWNNNWWMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWWNNNNWMMMMMMWXOxo;.        ...... ..    ..    .              ...oWMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNNNWWMMMWNNNNWMMMWWNNNNWMMMWWNNNWWMMMWNNNNWWMMMWNNNNWMMMMMNx'   .... .oWMMMMWNNNNWW
MMMWWNNNNWMMNO,..'...   .c0WMMMMWWWNNNWWMMWWNNNNWWMMWWNNNNWMMMWWNNNWWMMMWWNNNWWMMMWNNNNWWMMWWNNNNWMMMWWNNNWWMMMWWNNWMMXo,.               .........'...'..............      lNMMWWWMMWWNNNNWMMMWWNNNWWMMMWWNNNWWMMMWNNNNWWMMWWNNNNWWMMWWNNNNWMMMWWNNNWWMMMWWNNNWWMMMWWNNNWWMMMWWMMW0:.  ..'.  ..cNMMWNWWMMMWW
MMMMWNNNNWMMWK; .,,'''..  .;dOXWMMWWWNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNWMM0;.....                   .''.......',''''.....      .dNMWMMMMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMMMMXo.   .''.. ...,0MMWNNWMMMWN
WWWWWWWWWWWMM0' .,','''''..  ..;lxKWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMk. ..'..  .........       .''.     .,''..             .lXMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMWKo'    .''.. .''.:XMMWWWWWWWWW
NNNNWMMMMWWMWx...''''''''''...    'o0NMMWWNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMMx.   .  ..'''''''''.      ...      ...                  :KMMWNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMMMMNk:.     .''.. .''..dWMMMMWNNNNNW
NNNNWWWWWWWMWo..''''''''''''''..    .;d0WMMMMMWWWNNNNWMMMWWNNNWWMMWWWNNNWWWWWWWNNNWWMWMWNNNNWWMWWWNNNNWMMWWWNNNWWWMMMWd.     .''''''''''..                      .....'..       ;KMMWNWMWMWWNNNNWWMMWWNNNWWMMWWWNNNWWMMMWNNNNWWWMWWNNNNWWMMWWNNNWWMMMWWNNNWWWMWWWNNNWWMMMMWO:      ..''.. ..,'.'OMMMMMWWNNNWW
MMMMWNNNNWMMNl..''''''''''''''''.      .cONMMMWWWMMMMWNNNNWMMMWWNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNWMNo....  ..'''''''''..      ......        ..'',''''''.       :KMMMWNNNNWMMMWWNNNNWMMMWWNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWWMMWXo.     ..'''.. .''''.,0MMWNNNWMMMWN
MMMMWNNNNWMMWo..''''''''''''''','..      .;oONMMMMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNWMXc....   .','',''''.     ......''.       .'''''''''.         lNMMWNNNNWMMMMWNNNNWMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMMWNkc.     ..''''.. ..''''.,0MMWNNNWMMMWN
WWWWWWWWWWMMX; .''''''''''''''''','......   .,okKWMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMK:       ..'''...       ..    ...        ..'''''..         'kWMWWWWWWMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMW0l'     ..'''''''...'''','.,0MMWWWWWWWWWW
NNNNWMMMMMMMk.  .'''''''''''''''''''''''''..    .:kNMMMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMMMWWWMMMMMM0,         .           ..    ...           ...           .kWMWNWMMW0x0WMWWMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMMMMNo.     ..''''''''...'''''''.,0MMMMMWNNNNNM
NNNWWWWWWMMWd.   .''''''''''''''''''''',''''..     ,d0XWMMWWNNWWWWWWWNNWWWWWWWWNNWWWWWWWWWNWWWWWWWNNNNWMMWOoxXWMMMMMW0:......               ..'....''.   .....          ....   .OMMWWMMXo. ,KMMWWWWWWNNNWWWWWWWNNNWWWWWWWNNWWWWWWWWNNWWWWWWWWNNWWWWWWWNNNWWWMMMMKc     ..'''''''''....'''''''.,0MMMWWWWNNNWW
MMMMWNNNNWMNl.......''''''''''',,''''''''''','..     .,o0WMMMMWWNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWWMN:  'o0NMMMX: .'''.... .........'''.''''''''... .'''''........'''''.  .OMMMMWO;   .OMMWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWWMMWO;   ...''''''''''.  .',','''..cNMWNNNNWMMMWN
MMMMWNNNWMMO,..''.  .',''''',''',''''''''''''''''..     .;lONMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWWMX;  ...,xNMNc....      .'''''','''...'''',''''.. ..'',,,''''.......   ,KMMMNo.    .OMMWNNNNWMMMWWNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMMWKd;.  ..''''''''','..  .''''''''..dWMWNNNNWMMMWN
WWWWWWWWMMWd..''''. ..''''''''''''''''''''''''''',''..      ,xNMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWMMX;  ... .;kNk,       .....''''''.. .'''''''''''.  ...'''...''.        ,KMMXo.     ,KMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWNNWWWWWWWMMMW0c.   ..',''''''''''..  .'''''''''..dWMMWWWWWWWWWW
NNNNWMMMMMNc..'''''....'''''''''''''''''''''''''''''''..     .:0WMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMX: ..'.....:kKx'   .''...''..''.......'''''..''. .....''...',.        :XW0;       :XMMMMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMMMNk:.    .''''''''''''..  ..''''''''''..dWMMMMMWNNNNWM
WWWWWWWMMMK:.'',''''..  .'''',''''''''''''''''',,'''''''...    .dNMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMNc ..''......;o;  .''...''....'........''''..... .'. .'.  ..'..       :0d.        :NMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWMMMMMNk;.    ..''''''''''''.. ..'''''''','''..dWMMWWWWWWWWWW
MMMMWNNWMMK;.'','''''.    .'''''''''''''''''''''''''''''','..    ,dKWMMMWWNNNWMMMMWNNNNWMMMMWNNNNWMMMWWWMNc .''''.....      ..  ....   .  ..... ....      ..   .               .'          :XMMWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMMWXOo;.   ...'''''''''''''.  .''''''''''''''..dWMWNNNNWMMMWN
MMMMWNNNWMXc.'''''''''...   ..''''''',,''''''''''''''''''''''..    .;lONMMWNNWWMMMWNNNNWMMMMWNNNNWMMMWWWMNc .'',''.                                                                        cXMMWNNNNWMMMWWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMWXkl'    ..'',''''''''''''.. ..'''''''''''''''..dWMWNNNWWMMMWN
NNNNWWWMMMK:.''''''''''''.... ....'''........''''''''''''''',''.      .:0WMMWWWNNNWWWWWWNNNWWWWWWWNNNWWMMNl .','..      .         ..                          ..                           cNMMWWWWWWNNNWWWWWWWNNNWWWWWWWNNNWWWWWWWNNNWWWWWMMWO,     ..''''''''''''''''....'''''''''''''''''..lNMMMWWWWNNNWW
NNNNWMMMMMO,',,',,'''''''''''.......  ..............'''''''''''''..     .oXMMMWNNNWMMMMWNNNNWMMMMWNNNNWMMWd. .''.                                                                         .dWMWWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMMXo.   ..''''''''''''''''''....''''''''''''''.''''.,0MMMMMWNNNNNM
WWWWWWWMMWd'''','''''''''''''''''..   .''''''.      .......'','''''.   . .,xXWMWWWWWWWWWWWWWWWWWWWWWWWWWMMK;  .'. ..                                                                      ,OMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMXx,  ..''''''''''''''''''.....'''''''''''''''..''''.,0MMWWWWWWWWWW
MMMMWNNWMNl.'''''''''''''''''''','.    .......      .'''.....'''''''..  .. .,oKWMMWNNNNWMMMMWNNNNWMMMMWNWMWx.  ......                                                                   .'oXMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMMWKd,  ..''''''''''',,'''''.....'''''''''',','''...'''..oWMWNNNNWMMMWN
MMMMWNWWMX:..'''''''''''''''''''''.          .     ..''''.. .'''''''''.  ..   'xNMMWNNNWMMMMWNNNNWMMMWWNWMMNkl;...          .                                                         .:kXWMMMWWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNNWWMMNOo:.....'',''''''''''',''......',''''''''',''''''''''''.'OMMWNNNWWMMMWN
NNNNWWMMMK;..'''''''','..   .....'..                    ... .''''''''''..      .;kNMMMWWNNNNWMMMWWNNNNWMMMMMMMWKxl;.       .'.                                                      'lONMMWWNNNWMMMWWNNNWWMMMWWNNNWWWWWWNNNNWWMMMWKx;    .''''',''''''''''''..  ..','''''''''''''''''''''','.,KMMMMWMWWNNNWW
NNNNWMMMMK;.'''''''''''.  .............                     .',''''''''''..      .,dKMMWNNNNWMMMMWNNNNWMMMMWNWWWMMWXOd:.  .''..    .'.                                            ,xXWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMW0l.    ..''','''''''''''''..  ..'''''''''''''''''''''''''','..xWMMMMMWNNNNWW
WWWWWWWMMO'..''''''''''. .'''......   .          ..         .',,,''''''''''..      .;0WMWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWk. .'..    .''.     ..                       ...          .kMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMW0l.    ..''''''''''''''''''....''''''''''''''''''''''''''''''. .dWMMWWWWWWWWWW
MMMMWNWMMO...''''''''''.  ...     ....           .'.        .''''''''''''''''..     .,kNMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMK, .'.    ..''.    .'..      ...             .'.          :KMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMKl.   ...''''''''''''',,''.....'''''''',,''''''''''''''''''''.   '0MMWNNNNWMMMWN
MMWWWNWMMO' ........'''.   ....    .''.   .....  ...  ..... .''''''''',''''''''..     .:0WMMWNNNNWMMMWWNNNWWMWWWWNNNWMM0' .'......''''.....'..    ..'''.      .     .'..       .lXMMWWNNNNWMMMWWNNNNWMMMWWNNNWWMWMWNNNNWMMNd'   ..'''''''''''''','''.. ..'''''''''''''''''''''''''''''... .  lNMWWNNNWWMMMWW
NNNNWMMMMX:........  ......'',.    .,'.  ..'''.   ..  .'''. .'''''''','''''''''''.      .xNMMMMMMWNNNNWMMMWWNNNWWMMMMMMO'  .'''''''''''''''''..''''',,''........    ....      .lNMWWNWMMMWWNNNNWMMMWWNNNWWMMMWWNNNWWMMMMWO;  ..''''''''''''''''''''.  .'''''''''''''''''''''''''''''.. ...'..xMMWWMMMWWNNNWW
NNNNWMMMMWd'''''''..       ..''.   .'''. .'''''.  .   .''.  .'',,'''''''''''''''''..     .cKMMMMMWNNNNWMMMMWNNNNWMMMMMMWO,  ..''''.....''''..............  ..                 :XMWWNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMKl. ..'','''''''''''','','.. ..''''''''''''''''''''''''''.......''''..OMMWWMMMWNNNNWW
WWWWWWWWMWx,''''...      ..  ...   .'''. .','',..     .''.  .'''''''''''''''''''''''.      ,OWMMWWWWWWWWWWWWWWWWWWWWWWMMWXx;. ...                                            ,0MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMNx'  ..'''''''''''''''''''.. ..''''''''''''''''''''''''''.......','',..,0MMWWWWWWWWWWWW
MMMMWNNWMM0;','.  ...''...''..     .'''...',,,'''.. ..'''.  ..''''''''''''','',,'',''..     .dNMMMMMMMWNNNNWMMMWNNNNWMMMMMMWOl,..                                          .c0WMMMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMMW0:   ...''''''''''''''''''.. ..''','''''''''''''''''''''.....'''''''',..lNMMWNNNNNWMMMWN
WWWWWWNWWMNl'''. ..,'''. .''''.    .''''..''''''''''''''..     .....''''',,,''','''''''..    .lKMMMMWWWNNNWWWWWWWWNNWWWWWWMMMMWNK0kxxxxkkd;                    .,coddoollld0WMMWWWWWWWWNNWWWWWWWNNNWWWWWWWNNNWWMMMXo.  ..'',''''''''''''''''.....''',,''''''''''''''''''''....''''''''''''..oWMMWWWNNWWWWWWW
NNNNWMMMMMWk,''. ..'',..  ....'.. ..,'''''''''''''''''''.    ....     ....'''''''''',''''..    ,kWMWWWWMMMWWNNNNWMMMWNNNNWWMMMMWWWWMMMMMMWo                    ;KMMMMMMMMMMMMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMMMMWO,  ..'''''''''''''''',''.....''',,,''''''''''''''''''.....''',''''''''''..oWMWWWMMMWNNNNWW
NNNNWMMMMMMXl''.  .'''.       .'..''''''''''''''''''''''.   .''''......   .''''''''''''''''..   .oXMMWMMMMWWNNNNWMMMWNNNNWMMMMWNNNNWMMMMMK,                    ;KMMMMMWWWWWWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMMMNo. ..'''''''''''''',''''.....'''''''''''''''',,''''''.....''''''''''''''''..oWMWWWMMMWNNNNWM
WWWWWWWWWWMMk,''.  .'..  ...   ..,''''''''''''''''''''''.   .'''',,'''..   .,''''''''''''''''.    ,xNMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMM0'                    ,KMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWO:..''''''''''''''''''''.. ..'''''''''''''''''''''''......''''''''''',''''''..xWMMWWWWWWWWWWWW
MMMMWNNNNWMMXl'''.      ..'''.  .',''..............','''.    .........'.   .,'''''''''''''''''..    :0WMWNNWMMMWNNNNNMMMMWNNNNWMMMMWNNWMM0'                    .OMMWNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWMMXo..'''''''''''''''''''''....'''''''''''''''''''''''.. ..'','''''''''''''''''..:XMMMWNNNNNWMMMWN
WWWWWWWWWWWMMXc''.......'',''.. .','...............'''''.             ..  ..'''''''''''''','''''.    'xNMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMk.                    .xMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMWk,..'''''''''''''''''''.....','''''''''''''''''''''.....',''''''''''''''''''''..xWMMWWWWWWWWWWWWW
NNNNWMMMMWNWMMk,',''''''''''''.  .'''............  .'''..  ......    ...   .'''''''''''''''',''''..    :0WMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWl ..  ...              dWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNWMMXl...'''''''''''''''''''.  ..''''''''''''''''''''''.....'',''''''''''''''''''''..;XMMWNNWMMMWNNNNWW
NNNNWMMMMWNWWMXc'''''''''''''''.  ..''..   .........'''.  .......   .''.   .'''''''''''''''',''''''.    ,OWMWNNNWMMMWNNNNWWMMMWNNNNWMMMMNc ....'''......       .dWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWWMNk,..''''''''''',,''','''....''',,''''''''','''''''....''''''''''''''''''''''''''..xWMWNNNWMMMWNNNNWW
WWWWWWNNWWWMMMWx,'''''''''''''''.  .''''........'''',''.............'''.   ...''''''''''''''''''''''.    .xNMMWWWNNNWWWWWWWNNNWWWWWWNWWMNc .'''''','''''..      oWMMWNWWWWWWWNNNWWWWWWWNNNWWWWWWNNWMMW0c...'''''''''''''''''''.. .''''''''''''''''''''''....'''''''''''''''''''''''''''..lNMMMWWWWNNNWWWWWWW
MMMMWNNNNWMMMMM0;''''''''',''''''. .'''''''''''''''''''''''''''''''''''.  .....'''','''''''''''''''''.    .:OWMMWNNNNMMMMWNNNNWMMMMWNNWMNc .''''''',''''''.     .OWMWNWMMMMWNNNNWMMMMWNNNNWMMMMWNWWMNd'..''''''''''''''''''''.  .''''''''''''''''''''.....',''''''''''''''''''''''''''..:KMMMMMMWNNNNNWMMMWN
WWWWWWWWWWWWWMMNo''''''',,,''''''. .''''''''''''''',''''''''''''''''','.  .''...''''''''''''''''''''''.     .oNMMWWWWWWWWWWWWWWWWWWWWWMMX; .''.'''''''''''.      :XMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWO:..''''''',,'''''''''''.. ..''',''''''',''''''......''''''','''''''''''''''''''''..;KMMMWWWWWWWWWWWWWWWW
NNNNWMMMMWNNNWMMKc',''''''''''''''...'',''''''''''''''''''''''''''''''.  ..'''.....''''''''''''''',,'''.     .lNMMMMWNNNNWMMMMWNNNNWMMMMk...''''''''''''''.      .OMMMWNNNNWMMMMWNNNNWMMMMWNNNWMMXo...'''''''''''''''''''..  ..''''''''',,,''''... ...'''''''''''''''''''''''''''''''.'kMMMMWNNNNWMMMWNNNNWM
NNNNWMMMWWNNNNWMWx,'',''''''''''''......''..'.....''.....................'''''''......''''''''''''''''''..     cKMMMWNNNNWWMMMWNNNNWMMMNl .'''''''''''''''.       lNMMWNNNNWMMMMWNNNNWWMMWWNWWMWO;...','''''''''''''''''.  ..',''''''''',,'''..   ..''''''''''''''''''''''''''''''''..oWMMMWWNNNNWMMMWNNNNWW
MMMWWNNNNWMMWWWMM0,..''','''''''''.. ....'..''.....'.   .    ..........'''''',''''''...'''''''''''''''''''.     ;0MMMMMMWWWNNNWWWMWWWMM0, .'''''''''''''','.      'OWMMMWWWWNNNNWWMMWWNNNWWMMMXo. .''''''''',''''','''.. ..'''''''''''''','.    ..'''''''''''''''''''''''''''''''''..;KMMWNNWMMMWWNNNWWWMMWW
MMMMWNNNNWMMMMWWMNc   ..'',''''''''.  ...'...'........ .'..  .''''','''''''''''''''''....',''''''''''''''''.     :KMMMMMMWNNNNWMMMMMMW0: ..''''''''''''''''.       .oXMMMMMWNNNNWMMMMWNNWWMMWO;  .'''''''''''''''''..   .''',,,,'''''''''..  ...''''''''''''''''''''''''''''''''''...kMMWNNNWMMMWNNNNNMMMMWN
WWWWWWWWWWWWWWWMMWx. ... ..'''''''''.  ......''.....'.  .''.  ..'''','''''''''''''''''....''''''''''''''''''..    'dXMMMWWWWWWWWMMMWKl.  .'''''.''''',,'''..     ..  ;OWMMWWWWWWWWWWWWWWMW0o;. ..'''''''''''''''''..  ..''',,',,''''''...  ..''''''''''''''''''''''''''''''',,''''..lNMMWWWWWWWWWWWWWWWWWWWW
NNNNWMMMMWNNNNWMMMNl..'........'''''..   .. ..''.....'. .'''..  ..'','''''''''''''''''''...'''''''''''''''''''.     lNMMWWMMMMMMMW0l.    .'''''.'''''''''....   .'..  .dNMWMMMMMWNNNNWMMWx.   ..''''''''''''','''.. ..''''''''''''''..  ...''','''''''''''''''''''''''''''',,'''''.'0MMMMMMMWNNNNWMMMWNNNNNW
NNNNWWMMWWNNNNWMMMMXc.'''''.......'''.   ... .'''......  .''''.    .',''','''''''''''''''....''''''''''',''''''.     cKWMMMMMMWXx;.    ..''''''..'''''''''...   .'''.   ;kWMMMMWWNNNWWMNd.   .'''''''''''''','''....'''',''''''''..   ..'''''''''''''''''''''''''''''''''''''''''..cNMMWWWWWWNNNWWMMMWWNNNWW
MMMWWNNNNWMMMWWNNWWMXl''''''''... ....  ......'''.....'.  .''''..   .'''''''''''''''''''......''''''''',''''''''.     'OWMMMNkc.   ...'',''''''..'''''''''..  .  .'''..  .oNMMWWWMMMMMXl.  ..''''''''''''''''''....'''''''''''..   ..'''''''''''''''''''''''''''''''''''''''''... .kWMMWNNNNWMMMWWNNNWWMMMWN
MMMMWNNNNWMMMMWNNNWMMO'.'''''''''....     ....''''....... ..'''''..  .','',''''''''''''''''....''''''',,''''''','.     .o0Ol'.  ..'''''''''''''..''''''''''.   .  .,'''....;OWMMMMMMMXc   ..'',''''''''''''''....'''''''''''.......'''''',,''''''''''''''','''''''''''''''....    ,0MMMWNNNNWMMMWWNNNNWMMMWN
WWWWWWWWWWWWWWWWWWWMMX:..'''',,'''''..     ....'''.......  .'''''''.....'',,'''''''''''','.''...''''''''''''''''''..     ......''''''''''''''''''''''''''''..  ....'''''''...c0WMMMW0;.  ..'''''''''''''''''. ..',,'''''''.....'''''''''''''''''''''''''''''''''''''.....     .. .dWMWWWWWWWWWWWWWWWWWWWWWWW
NNNNWMMMMWNNNNWMMMMMMWx..''''',,,'''''..    ......'.....'.  .''''''''....','''','''''''''''''...''. ..'''''''''''''.     ..','''''''''''''''''''''''''''''''....''''''''',''. .c0WWO,   .''''''''''''''''''....''''''','.   .','''''''''''''',''''''''''''',''....  .........''..cXMMWNWMMMMWNNNNWMMMWNNNNNW
NNNWWWWWWWNNWWWWWWWWMMNo..','''''''''','.        .''....... .'''','',''....'''''''''''''''''''.....   ..''''''''...   ...''''''''''''''''''''''''''''''''.'''''''''''''''''''.  .;:.   .'''''''''''',,''''. .''',''''''.  ..'','''''''''''''''''''''''''''....   ....'''''''''..,OMMWWNWWWWWWNNNWWWWWWWNNNWW
MMMMWNNNNWMMMMWNNNNWMMMK; .''''''''''','.  .      .''.'....  .''','''''''........''''''''''''''.....   ..''''...    ..'''''''''''''''''''''''''''',''''''..',,'''''''''','''''..       ..''''''''''''',''. ..''''''''..  .''''','''''''''''''''''''''....     ...''''',,,'''''..dWMMMMMWNNNNWMMMWWNNNWWMMMWN
MMMMWNNNNWMMMWWNNNNWMMMWl..''','''''''''.. ...    .''''....  .'''''''''''''..    .''''''''''''''...'....'''.      ..''''''''''''''''''''''''''''''''''''''...''',''''''''',,''''..       ...''''',,'''''. ..'''''''... ..''''''''''''''''''''''''....    ....'',''''''''''''...lXMMMMMMWNNNNWMMMWWNNNWWMMMWN
WWWWWWWWWWWWWWWWWWWWWWMWx.  ...''''''''''.  ...   ..,''.....  .''''''''''',''.......'''','''''''....''..'..    ..'''''''''''''''''''''''''''''''''''''..'''...'','''''''''''''''''...       .'''''''''....''''''''.   .''''''''''''''','''''''...   ....''''''',,''''''''''..'dXMMWWWWWWWWWWWWWWWWWWWWWWWWWW
NNNNWMMMMWNNNNWMMMWNNNWMXl.  . ...'''''''..  ...   .'.....'..  .'''''''''''''''''....',''''''''''...'''..   ..'''''''''''''''''''''''''''''''''',''''''''''..'''''''''''''''',,,'''''..      .'''''''.  .''''''''.  ..'''',''','''''''''''.........''',',,''',''''''''''''. ,OWMMMWNNNNWMMMMWNNNNWMMMWNNNNWM
WWWWWWWWWWWWWWWWWWWWWWWMMNo. .........''''.   ...   ....',''.  .'''''''''''''''''''....'''''''','...''.   ..'''''''''''''''',''''''''''''''''''''''''.......'','''''''''''''''''''''','.      .'''''.  .'','''''.  ..''',,''''''''''''.......'''''''''''',,'''''''''''''''..kWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMMWNNNNWMMMWNNNNNWMMMMMMNd.  ..'..........   ..   ....'''''.  ..'''''''''''''''''''....'''''''''...  ...''''''''''''''''''''''''''''''''''''''''''........'''''''''','''''''''''''''''..     ..'..  .',',''''.. .'',''',''''''''''..  ...''''''''''''''''''''''''''''''. cNMWWNNWMMMMWNNNNWMMMWNNNNNWMMMWN
MMMMWNNNNWMMMWWNNNNWMMMWWWMW0l. ..''''.....    ...  .....''''..   ....','''''''''',''''...''''',''.   .'''''''''''.''''''''''''''''''''''''''''''''''.......'''''''''''''''''''''''''..'''..         .'''''''.....''''''''''''''''......'''''''''''''''''''''''''''''','. .xWMWNNNWMMMMWNNNNWMMMWWNNNNWMMMWN
NWNNWWWWWWNNNNWWWWWWNNNWWMMMMWO,  .''''',''..        ..'..''''.       ..''''''''',,''''''..'''''..  ..'''''''''''...''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''',''. ..'','.        .'''''.....''''''',''''''''....'','''''''''''''''''''''''''''''''...:OWMMMWWWWWNNNWWWWWWNNWWWWWWWWNNNWW
NNNNWMMMMWNNNNWMMMWNNNNNWMMMMMMXl. ..''',,,,'.   ..   .''''''''.  ........'''''''','''''''.....    .'''''''''''....''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''..  .'',''.        ..''....''''''','''''''''.  .''''''''''''',,''''''..''','''''''...oXMMWWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWO;.  ..''''''.  ...  ..'''''''.  .''''.. ..'''''''''''''''.     ..'''''''''''..  ..''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''.  ..'''''.         .....''''''''','''''..   .'''''''''''''''',,'......''''''''...c0WMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMMW0d:.....''''. ... ...'''''''..  .'''''.. .'''''''''''''''.   ..'''''''''''.    ..,'''''''''''''''''''''''''''''''''''''..''...''''''''''''''''''.    .''''''.          .'','''.''''',''..   ..'''',''''''''''',''.   .''',''''...;kNMMMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWN
MMMMWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWWMMWKd'   ..'.. .. ..'''''''''.   .'','''.....''''',''''''.  .''''''''''''..    ..''''''','''''''''.''',,'''''''''''''''..''''''''''''''''''''''.     .'''''''.         .'''''''''''''.. ...''''''''',''''''''''''....',''''''..,dXMMWWMMMMWNNNNWMMMWWNNNNWMMMWWNNNNWMMMWN
NNNNWWMMWWNNNWWMMMWWNNNWWMMMWWNNNWWMMMMMKc.   .'.  ....''''''''''..  .''',''..  ..''',,''''. ..''''''''''...      ..',''.'''',,'',''...'''''''''''.''''''''''''''''''''''''''''''..     .'''''''..         .'''''''''.. ...'''''''''''',,,''''''''''''''''',''...cKMMMMMWNNNNWWMMMWNNNNWMMMWWNNNWWMMMWWNNNWW
NNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMMMMN0d;. ...  ...''''''''''''....'','','.....''''''.....',''''','.          ..''''.'''''''','''''''''..'''''...'''''''''.''''''''''''''''''...    ..,'',,'.           .''','''.   .'''','''''''''''''''''.''',''''',''...cONMMMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMNd. ... ....''',''''''''....,'''''''....''...  .''''',''''.           ..,','.''''''''''''''''''..'''''....'''''''...'''''''''''''''''.       .''''''..          .'''''..   ..''','''''''''''''''''''''''''''','..;OWMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMMMWk. ... ....',,''''',''.. ..''''''''.....  ...'',''''''..             .''''.''''''''''''''''''''''''''...''''''''.'''''''''''''''''..       .''''''''.          .''..   .'''''''''''''''''''''''',,'''''''''...lXMMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWN
MMMWWNNNNWMMMWWNNNNWMMMWWNNNWWMWWWNNNNWMMMWWMMWk. ..  ....'''''''''''.   .''''''''.   ..'''',,''','.               .'','.','''''','.'''''''''''''''''''',''''''''''''''''''',''''..      .'''''''''.          ..    .'''''',''''''''''''''''',''',''''''..,kWMMMWMMWNNNNWWMMMWNNNNWMMMWWNNNNWMMMWWNNNWWMMMWN
NNNNWMMMWWNNNNWMMMWWNNNWWMMMWNNNNWWMMMWNNNNWMMMWd. ..  ....'',''''''''.  ..'''''..   .''''''''',''.                .''''.'''''','''.''''''''''.'''''''''''''''''''''''''''''''''''..     .'''''''''.              ..''''''''''''''''''''''''','''''''''..:0WMMWNNNNWWMMMWNNNNWWMMWWNNNNWMMMWWNNNWWMMMWWNNNWW
NNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMNd. .  .....'',,'''''''.. .''''.  ...'''''''''.''.                 .'','.'''''...'..'',''',,,'..'''''''''','''''''''''''''''''''''.      .'''''''''.            .''''''''''''''''''''''''''''''''''''...dXMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWO,    .....'''''''''''.. .... ..'''''''''''. ...                 .''''.''''.   ....''''''''''''''''...''''''''''''''''''..  .'''.      .'''''''''.            ..'''''''''''''''''''''',,'''''''''...c0WMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMXx:.  ..'...'''''''''''..   ..',''''''''''.        ..           .'''''''''.. .....''''''''''''''''....''''''''''''''''..   .''...     ..'',,'''''.            ..'''''''''''''''''''''''''''''''..;kNMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWN
WWWWWWNNNWWWWWWNNNWWWWWWWNNNWWWWWWWNNWWWWWWWNNNNWWWMMW0c.  .'...''''''','''.  .'',,'''''''....      .....          .''''''''''.'''..''''''''''''''''''..'''''''''''''''','.. ..',....     .''''''''''.            .'''''''','''',,''''''''''''.....lXMMWWWWNNNWWWWWWWNNNWWMWWWNNNWWWWWWWWNNWWWWWWWNNNWWWWWWW
NNNNWMMMWWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNWMMNk;  .'...''''',,'''..''''''''''''....      ... ..          .''''''''''.'''...'''''''.''.'''''''''''''''''''.'''''',''''''...'.    .''''''''''..           .''''''''''''',,'''.........   .lXMWWNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWW
NNNNWMMMMWNNNNWMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMXc  .'...''',,''''''''''''''''''. .     ...               .''''''''''.'''...'''.'''.''.''''''''''''''''''...''''''''''''.....    ..''''''','.             .'''''''''''.....   .......  .xNMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMXc  .''..'''','''''''''''''''...                         .',''''''''.'''...''..'''.''.''''''.''''''''''''.'''''''''''......      .'''',,'''.             .'''''''............'''''.  ,OWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNWMM0, ..''...'''''''''''''''''...                          ..'''''''''.','...''..''..''.''''''.''''','',''''''''''''''''......     .''''''''..             .''''.......''''''''''''. .:0MMWNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWN
WWWWWWNWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWMWO' ..''....'''''''''''''''.                             .'''''''''.'''...''..''..''.'''''''''''''''.'''''''','''''''. ..'..    .'''''','..              .'.. .'''''''''''''','...oNMMMWNWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
NNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMMMWO' ..''....'''''''''''','.                             .'''''''''.'''...''..''..'.......'''''''''....''''''''''''''....''.    .'''''''''.              .. ..'''''','''''''''...oNMMMMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWW
NNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWWMWx.  .'''...''''''''''''.                             .''''''''''.''''..''...''..    ....'''''',''. ..','''''''''''. ..'..    ..'',''''''.               .''''''''''''''''...:OWMMWWMMMWWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWW
WWWWWNNNWWWWWWWWNNWWWWWWWNNNWWWWWWWNNNWWWWWWWNNWWWWWWWNNNWWMMMNl   .','...''''''''''..                             .'''''''''''''''..''....     ..'...,''''''''.  ....''''''''''. .''.      .'''''''..               ..'''''''''''''''. .lNMMMMWWNNNWWWWWWWNNNWWWWWWWNNNWWWWWWWNNNWWWWWWNNNWWWWWWWNNNWWWWWWW
MMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMNl. ..''''...''''','..                              .'''''''''''''''.'''...     .'''...''''''''.     . .''',''''.  .','.     .'''''''..               .'''''''''''''''.  '0MMMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMNo. .'''''....'''..                                .''''''''''''''''''''..    .''',....'''''''.        .''''''.   .''''.    .''''''''..               .'''','''''''..   oNMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
NNNNWMMMMWNNNNWMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNMMNo. .''''''.....                                  .''''''',''''''''''''.    ..'',''...',''''.. ...     .'''''.  ..''''.    .''.''''''.               ..''',''''''..   ;KMMWNNNNWMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWM
NNNNWMMMWWNNNNWMMMWWNNNWWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMNl  .'''''''.           ..                       .'''''',,'''''''''''.    ..''''''....''''''...''.     ..''''. ..'','.     ....''''''.               .''''''''''.   .xWMMWNNNNWMMMWWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWWNNNWW
MMMWWNNNNWWMMWWNNNWWMMMWWNNNWWMMWWNNNNWWMMWWNNNNWWMMWWNNNWWWMWWWWWMXl. .''''..           ..'. ...                  ..''''''''''''',,','.    .''''''''...''''''..''''.      ..'.   .'''..     ....'..''...              .''''','...    ;KMMWWWWMWWNNNWWMMWWWNNNWWWMWWWNNNWWMMWWNNNNWWMMWWNNNNWWMWWWNNNWWWMMWW
MMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMNNWWMNl. .''...         ...''.....                   .''''''''''','''''..  ..'''''''''....'''''..''''..      ..    .''''.      .  .....                  ...'''.      ;0MMWNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMXl. ...;xl.      .............'..              .'''''''''''''''..   ..''''''''''....'''''..'''''..          ..',''.                                  ..         ;0WMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
NNNNWMMMMWNNNNWMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMMMNk;..oXWx.     .........''''''..              .',,'''''''''..     .''''''''''.'....'''''..''''''..        .''''',..                                             .cOWMWWNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWW
NNNNWWMMWWNNNNWMMMWWNNNWWMMMWWNNNWWMMMWNNNNWMMMWWNNNNWMMMWWNNNWWMWMWWWMMNO0N0l.   ..''''''''',''..........          .','''','''''.     .''''',''''..'....'''''..'''''''..        ..'',,'.                                               .oNMMWNNWMMMWWNNNWWMMMWWNNNWWMMMWNNNNWMMMWWNNNNWMMMWWNNNWWMMMWNNNNWW
MMMWWNNNNWMMMWWNNNNWMMMWWNNNWWMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWWNNNWWMMWKxl;.    ...............   ........         ...........'..    ..'''......'........''.............          ..'''.                                                 :KMMMWWNNNWWMMMWWNNNWWMMMWNNNNWWMMMWNNNNWMMMWWNNNNWMMMWWNNNWWMMMWN
MMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMM0,   ...',;;;;::cc;.....'''''',,,,''.........'''''''''...                         .                          ....      ...........',:cclllllclllloooooolc;;:ccc::;,:OMMMWWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMN0xxO0XNNNWWWWWWMMWX00KXNNNNNNNNNNNNXXXXXXXXNNXXXXXXXXX0OkkkxxxxxxxxxxxxxddoodxxxkkxdoloooooooooooooddoccldxO000kxxxxxOKKXXXXKK00XNWMMMMMMMMMMMMMMMMMMMMMWWMMMMMMWWWWMMMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
NNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNWMMWN0kdlcccclok0NWMMMMMMMNKkdolccccclokXMMW0xolcccccclox0NMMMMMMMMWXOxolcccccodOKWMMMMMMMMMMMMMMMMMWN0kdlccccclox0XWMMMMMMMMMMMMMWN0xolccccldk00Ok0NMMWXOxxxxxxxxxxxxxxxxxxdolclkNMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNM
NNNWWWWWWWNNNWWWWWWWNNNWWWWWWWNNNWWWWWWNNNNWWWWWWWNNWWWWWWWWWMWKxc'.          .';:::xXWO,.            ;0No.            .oNMMMMNOl,.            .,lONMMMMMMMMMMMWKxc'.            .:dKWMMMMMMMMNOc'.           .  .:0WX:                         lXMMWWNNNWWWWWWWNNNWWWWWWWNNWWWWWWWNNNWWWWWWWNNNWWWWWWWNNNWW
MMMMWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNWMMWOc.                     :0k'            .lXNx'            'xWMMXd,                   .;kNMMMMMMMW0c.                   .c0WMMMMWO;          ..        .kXx:.           .'''...     .kMMWWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWN
MMMMWNNNNWMMMWWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNWMMKl.        'cll:,.         lNXx.         :KWMMMXc         .dNMMWO,        ,cl:.           :x0WMMMXo.       .;lc,.          .dNMMWx.         ;kKKOd;.     ;KMWk.        .kXNNNNX0x;   .dWMWWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMM0,        'xNMMMMW0o.       ,KMX:        .xWMMMMMO.        ,KMMWx.       .dNMMWKo.           'OWMXc        ,OWMMNO;           cXMK,          :KWMMMW0c.   :XMMNc        ;XMMW0oo0WNx;,oXMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
NNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMK,        .xWMMMMMMMMK:      :XMNc        .dWMMMMMO.        ,KMMO.        :XMMMMMWk.           ,0No        .dWMMMMMXl           lN0'           .;cdk0NNKxoxXMMMWo        :XMMX;  'OMMWWMMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWM
WWWWWWWWWWNWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWo         .OMMMMMMMMMMXo'...c0MMNc         .:cccc:'         ;XMNc         ;XMMMMMMWd.           lO'         dWMMMMMMX:          .kNl                ..;oONMMMMMMd        .oxxc.   oWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWW
MMMMWNNNNWMMMWWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWMMX;         .xWMMMMMMMMMMWXKKXWMMMWl                          :XMK,         .kMMMMMMMX:           ,l.         ;XMMMMMMMO.          oWXl.                   ,xNMMMMd.                cNMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWN
MMMMWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMMWMMX;          :XMMMMMMMMMMMMMMMMMMMWl          ...''..         :NMK,          cXMMMMMMMk.          ,l.         .xWMMMMMMNc          lWMNk:.                   cXMMMd.        ...     lWMMMWWWNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWN
NNNWWWWWWWWNNWWWWWWWNNWWWWWWWWNNNWWWWWWWNNNWWWWWWNNNWWMMWo           cXMMMMMMMMMMMMMMMMMMWl         lKXNNNNx.        cNMNl          .dWMMMMMM0'          :k,          '0MMMMMMWd.        .xXkkXN0d:'.               .xWMMd.       .xXXx.  .kMMMMWWMMWWWNNWWWWWWWNWWWWWWWWWNNWWWWWWWWWWWWWWWWWNWWWWWWWWWNNWWW
NNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMK;           ,kNMMMMMMMMW0ocxNMMNc        .kMMMMMMO.        cNMMO'          .xWMMMMM0,         .kNo.          ;0MMMMMWx.        :0c  'xNMWN0koc'            oWMWo        '0MMWd.'dNMMXd;;dNMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMW0,            'cdxkkxdc,.  '0MMK,        .xMMMMMMx.        ;XMMWk.          .oKWMMXl.        .xWMXl.          'kNWMW0,        ;0X:   .cKWMMMMMNd.         .kMMNc        .OMMMWXNWMMKc   .OMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNWMMKc.                       :XMNd.         ;0WMMWK:         .xWMMWO;           .;c:'        ;oOWMMMNd.           ':c;.       .lXMWx.    .:dk0K0k:.        .oNMM0'         c0XNNXXKkl'    ,KMMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWN
MMMMWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNWMMWO:.                   .cKNx'            .dNNd.           .;OWMMXx,                   .;xNMMMMMMMWKl.                   .c0WMMMNl         ..          ,kNW0o'           .......      .xWMMMMMWWNNNWWMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWWNNNWWMMMWN
NNNNWWWWWWNNNWWWWWWWNNNWWWMWWWNNNWWMMWWNNNNWWMMWWNNNNWWMWWWMMMWKd:'.          .':lx0WMNo.            .dNNl.            'kWMMMMNOl;.           ..:d0WMMMMMMMMMMMWXxc'.           .,cxKWMMMMMMNk:'.             .,lONMMNl.                        .dNMMWNNNWWMMMWNNNNWWMMWWNNNNWWMWWWNNNNWWMWWWNNNWWWWWWWNNNWW
NNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMMWXXXXXK0koc;,'..';cx0NMMMMMMWKkdolc,.  .'oKWMMN0xolccccclodxxxkO00000Okd:,...    ..lKWWKOxddoooooodxk0NWNKkdo:..   .':okKWMWKkkO000Okdc;'....   ..'lKMWKOxdc'....',;cdkkkkkkd:,'..   ;xKWMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWO;.............    ...,cdKWMMMMMMMXo.     .:kWMMMMMMMMMMMMWKc.                      .ONd.             .;0MMMMX:          .xXo.                      .dXo.            .;0MMMMK:          .xWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMMWNNNNWMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNWMWO;.                      .c0WMMMMMk.        .lXMMMMMMMMMMM0;                       .lXNd.             .:0MMMMNx:.       .lkc                        :KNo.            .:KMMMMNx;.       'lKMMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWN
MMMWWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMWWNWWMMNKo.        .oOxl.        'kWMMMMd.          ;0MMMMMMMMMNc     'lkOOx,           .oNMMWK:           ;0NMMMMMMMWO'     ;KWd.    .cxOOk:            cKMMW0:          :0WMMMMMMMWO'     ;KMMMMMMMWWNNNWWMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWWNNNWWMMMWN
NNNNWMMMWWNNNNWMMMWWNNNWWMMMWNNNNWWMMMWNNNNWMMMWWNNNNWMMMMWMMK,        ,KMMWO'        :XMMMNc            ,OWMMMMMMMX:    :KMMMWk'          .dNMMMMMk.         .dMMMMMMMMMMN:     cNWo    'OWMMM0;          .lXMMMMMx.        .xMMMMMMMMMMX:     lWMMMWNNNWWMMMWNNNNWWMMMWNNNNWWMMWWNNNNWMMMWWNNNWWMMMWWNNNWW
NNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWWMX;        ,KMMMNc        ,KMMWx.             'OWMMMMMMW0c''oXMMMNx.          .kWMMMMMMk.         .xMMMMMMMMMMNc     cNMXo'.c0WMMWO,          .oNMMMMMMk.        .kMMMMMMMMMMN:     lWMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMX;        ,KMMM0,        :XMMO'   .;'         'OWMMMMMMMWNNWMMMNo.          'OWMMMMMMMk.         .xMMMMMMMMMMNl     cNMMWNNWMMMWk.          .xNMMMMMMMk.        .kMMMMMMMMMMNc     lWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMX;        .d0Od,        'OWM0,   .kWXl.        'OMMMMMMMMMMMMMXl.          ;0MMMMMMMMMk.         .kMMMMMMMMMMWl     cNMMMMMMMMNd.          .kWMMMMMMMMk.        .OMMMMMMMMMMNl     lWMWWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWN
WMWWWNNNNWWWWWWNNNWWWWWWWNNNWWWMWWWNNNWWWWWWNNNWWWWWWWNNNWWMMX;                    .cKWMK;   .dWMMNo.        ,0MMMMMMMMMMMK:           :KMMMMMMMMMMk.         .OMMMMMMMMMMWl     cNMMMMMMMNo.          ,OWMMMMMMMMMx.        'OMMMMMMMMMMNl     lWMWWWWWWWWNNNWWWWWWWNNNWWMWWWNNNNWWWMWWNNNWWWWWWWNNNWWWWWWW
NNNNWMMMWWNNNNWMMMWWNNNWWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMWWMMX;               ..'cdKWMMX:    .cxxxxc.         ;KMMMMMMMMW0;           cXMMMMMWNWMMMk.         .kMMMMMMMMMMNl     lWMMMMMMXc           ;0MMMMMWWWMMMx.        .OMMMMMMMMMMNc     oWMMWWNNNWWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWW
NNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWMMK;        ,k0OOOO0XNMMMMMXc                       ;KMMMMMMWk'          .oNMMMMWO:';dXMO.          lNMMMMMMMMMX;     dWMMMMMK;           :KMMMMMKl,,lKMk.         oNMMMMMMMMMK,    .dWMMMNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMK,        ;XMMMMMMMMMMMMNl                         :XMMMMWx.          .oNMMMMWk'   .xMK;          .c0WMMMMMW0:     .kMMMMWO,           cXMMMMM0;    lNK,         .lKWMMMMMW0:     .OMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MMMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNWWMM0'        'OMMMMMMMMMMMXl.    ,xOO00OOkxl.          cXMMNd.           'x0K0Oxc.    .xMWk.           .;loooc,.     .oNMMMWk'           .o0K0Oxl.     lNWx.          .;lodoc,.     .oNMWNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWN
WWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWNWWWWWWNWWWWWWWWWWWWMW0o'          'l0WMMMMMXkl'      'o0WMMMMNOl.           'cd:.              ...        ,KMMWOo;.                     'xNMMMWx.              ...        .kMMWO;                      'xNMMWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWW
NNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMNo.             cNMMMMWo           cXMMMM0,                                          ,OWMWMMMNOl,.              .'cxXMMMMM0'                         .xWMMMMNOl,.              .'ckXMMMMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWW
NNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMMNkoc:;;;;;;:cokXMMWWMMKdc:;;;;;:lxKWMMMMW0occ:;;;;;;;:clxkxooodoooooooooooooooool::dKMMWNNWWWMMNKkdlc:;;;;;clox0NWMMMWWWMNkdoooooooooooooooooodol:;l0WMMMMMMMMNKkdlc:;;;;:clok0NMMWWWWMMMWWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWW
WWWWWWWNWWWWWWWWWNWWWWWWWNNNWWWWWWWNNWWWWWWWWNWWWWWWWWWWNWWMMMMMWWWWWMMMMMWWWWWMMMMMMWWWWWMMMWWWWWMMMMMMMWWWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMWWWWWWWWWWWWWMMMMWWWWWMMMMMMWNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMWWWNNWMMMMMMMMWWWWMMMMMWWMMWWWWWNNWWWWWWWNNNWWWWWWWNWWWWWWWWWNNWWWWWWWWWWWWWWWWWNNNWWWWWWW
MMMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWWWWWMMMMWNNNNWMMMMWWNWWWMMMMWNNNNWMMMMWWWWWMMMMMWWWNWMMMMWNNNNWMMMMWNNNNWMMMMWWNNNWMMMMMWNNNNWMMMMWWWWWMMMMWNNNNWMMMMWNNNNWMMMMWNNNWWMMMMWNNNWMMMMWNNNNWMMMMWWNWWWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNWMMMWN
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
NNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNNMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNNWMMMWNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMNNNNNWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWNNNNWM
NNNNWMMMWWNNNNWMMMWWNNNWWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMWWNNNNNWMMMWWNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMMWNNNNWMMMWWNNNWWMMMWNNNNWWMMMWNNNNWMMMMWNNNNWMMMWWNNNNWMMMWNNNNWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW`;
